### ISSUE TITLE
mu4e

### ISSUE THREAD

**Issue by tsdye** [alezost/alect-themes#12]
Aloha Alex,

By chance, I saw this in *Messages* while using alect light.

Invalid face attribute :inherit mu4e-contact-face [3 times]

I'm using spacemacs, with this version of emacs: GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21)
 of 2017-09-22, modified by Debian

All the best,
Tom

**Comment by alezost** [comment]
Hello Tom,

Sorry for the long delay.  I don't use mu4e, so I'm not sure what can cause this, but is it only with alect-themes?  `mu4e-contact-face` is defined in a usual way, so I don't see how it can be a problem.

May it be that the problem is in mu4e itself?  I see several ``:inherit mu4e-contact-face`` lines here:

https://github.com/djcb/mu/blob/master/mu4e/mu4e-compose.el#L416

Perhaps this is the real cause of the error, although I really don't know, sorry.

**Comment by tsdye** [comment]
Thanks for looking into this Alex.  

All the best,
Tom
